% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
%                                                                  
% Parameter Definition File                                        
%                                                                  
% Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor  
%       (http://www.cs.vt.edu/~asandu/Software/KPP)                
% KPP is distributed under GPL, the general public licence         
%       (http://www.gnu.org/copyleft/gpl.html)                     
% (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa           
% (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech            
%     With important contributions from:                           
%        M. Damian, Villanova University, USA                      
%        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
%                                                                  
% File                 : mech_Parameters.m                         
% Time                 : Mon Jan 24 15:35:18 2022                  
% Working directory    : /home/sahmed/mechanism                    
% Equation file        : mech.kpp                                  
% Output root filename : mech                                      
%                                                                  
% ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~




% NSPEC - Number of chemical species                               
 global NSPEC; NSPEC = 173; 
% NVAR - Number of Variable species                                
 global NVAR; NVAR = 167; 
% NVARACT - Number of Active species                               
 global NVARACT; NVARACT = 146; 
% NFIX - Number of Fixed species                                   
 global NFIX; NFIX = 6; 
% NREACT - Number of reactions                                     
 global NREACT; NREACT = 513; 
% NVARST - Starting of variables in conc. vect.                    
 global NVARST; NVARST = 1; 
% NFIXST - Starting of fixed in conc. vect.                        
 global NFIXST; NFIXST = 168; 
% NONZERO - Number of nonzero entries in Jacobian                  
 global NONZERO; NONZERO = 1996; 
% LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
 global LU_NONZERO; LU_NONZERO = 2511; 
% CNVAR - (NVAR+1) Number of elements in compressed row format     
 global CNVAR; CNVAR = 168; 
% NLOOKAT - Number of species to look at                           
 global NLOOKAT; NLOOKAT = 173; 
% NMONITOR - Number of species to monitor                          
 global NMONITOR; NMONITOR = 0; 
% NMASS - Number of atoms to check mass balance                    
 global NMASS; NMASS = 1; 

% Index declaration for variable species in C and VAR              
%   VAR(ind_spc) = C(ind_spc)                                      

 global ind_DUMMY; ind_DUMMY = 1; 
 global ind_NOCl; ind_NOCl = 2; 
 global ind_BrNO; ind_BrNO = 3; 
 global ind_OBrO; ind_OBrO = 4; 
 global ind_CH3Cl; ind_CH3Cl = 5; 
 global ind_CO2; ind_CO2 = 6; 
 global ind_SULF; ind_SULF = 7; 
 global ind_ClONO; ind_ClONO = 8; 
 global ind_CH3; ind_CH3 = 9; 
 global ind_HCO; ind_HCO = 10; 
 global ind_ClOO; ind_ClOO = 11; 
 global ind_CCl3; ind_CCl3 = 12; 
 global ind_C2H5O; ind_C2H5O = 13; 
 global ind_C2H4O2; ind_C2H4O2 = 14; 
 global ind_CH2CCl3; ind_CH2CCl3 = 15; 
 global ind_CH3SCH2; ind_CH3SCH2 = 16; 
 global ind_CH2Br; ind_CH2Br = 17; 
 global ind_BrOO; ind_BrOO = 18; 
 global ind_CH32SBr; ind_CH32SBr = 19; 
 global ind_CH3SOCH3; ind_CH3SOCH3 = 20; 
 global ind_CHBr2; ind_CHBr2 = 21; 
 global ind_CHBrCl; ind_CHBrCl = 22; 
 global ind_H; ind_H = 23; 
 global ind_CBr3; ind_CBr3 = 24; 
 global ind_CH3CCl2; ind_CH3CCl2 = 25; 
 global ind_CH2Cl; ind_CH2Cl = 26; 
 global ind_CHCl3; ind_CHCl3 = 27; 
 global ind_SO2; ind_SO2 = 28; 
 global ind_CH3CCl3; ind_CH3CCl3 = 29; 
 global ind_ISHP; ind_ISHP = 30; 
 global ind_C2H5O2; ind_C2H5O2 = 31; 
 global ind_CCl4; ind_CCl4 = 32; 
 global ind_CH2Br2; ind_CH2Br2 = 33; 
 global ind_CHBr3; ind_CHBr3 = 34; 
 global ind_CH2BrCl; ind_CH2BrCl = 35; 
 global ind_NO3Aer; ind_NO3Aer = 36; 
 global ind_HC8; ind_HC8 = 37; 
 global ind_ACE; ind_ACE = 38; 
 global ind_HC5; ind_HC5 = 39; 
 global ind_MAHP; ind_MAHP = 40; 
 global ind_NALD; ind_NALD = 41; 
 global ind_O1D; ind_O1D = 42; 
 global ind_CH3Br; ind_CH3Br = 43; 
 global ind_ETEG; ind_ETEG = 44; 
 global ind_HONO; ind_HONO = 45; 
 global ind_BrNO2; ind_BrNO2 = 46; 
 global ind_HNO4; ind_HNO4 = 47; 
 global ind_BAL2; ind_BAL2 = 48; 
 global ind_TR2; ind_TR2 = 49; 
 global ind_XYO; ind_XYO = 50; 
 global ind_XYM; ind_XYM = 51; 
 global ind_XYP; ind_XYP = 52; 
 global ind_CH3SCH3; ind_CH3SCH3 = 53; 
 global ind_MCT; ind_MCT = 54; 
 global ind_XY2; ind_XY2 = 55; 
 global ind_XYO2; ind_XYO2 = 56; 
 global ind_PPN; ind_PPN = 57; 
 global ind_MPAN; ind_MPAN = 58; 
 global ind_ClNO2; ind_ClNO2 = 59; 
 global ind_ETH; ind_ETH = 60; 
 global ind_HC3; ind_HC3 = 61; 
 global ind_EOH; ind_EOH = 62; 
 global ind_TOL; ind_TOL = 63; 
 global ind_OP1; ind_OP1 = 64; 
 global ind_PHEN; ind_PHEN = 65; 
 global ind_Br2; ind_Br2 = 66; 
 global ind_ISON; ind_ISON = 67; 
 global ind_ORA1; ind_ORA1 = 68; 
 global ind_CHO; ind_CHO = 69; 
 global ind_PAA; ind_PAA = 70; 
 global ind_HBr; ind_HBr = 71; 
 global ind_ClETEP; ind_ClETEP = 72; 
 global ind_BrCl; ind_BrCl = 73; 
 global ind_API; ind_API = 74; 
 global ind_PAN; ind_PAN = 75; 
 global ind_MCTO; ind_MCTO = 76; 
 global ind_H2O2; ind_H2O2 = 77; 
 global ind_BAL1; ind_BAL1 = 78; 
 global ind_OClO; ind_OClO = 79; 
 global ind_Cl2; ind_Cl2 = 80; 
 global ind_N2O5; ind_N2O5 = 81; 
 global ind_HOBr; ind_HOBr = 82; 
 global ind_LIM; ind_LIM = 83; 
 global ind_BALP; ind_BALP = 84; 
 global ind_BrONO2; ind_BrONO2 = 85; 
 global ind_ISO; ind_ISO = 86; 
 global ind_CO; ind_CO = 87; 
 global ind_EPX; ind_EPX = 88; 
 global ind_DIEN; ind_DIEN = 89; 
 global ind_ETE; ind_ETE = 90; 
 global ind_ClONO2; ind_ClONO2 = 91; 
 global ind_TLP1; ind_TLP1 = 92; 
 global ind_XYL1; ind_XYL1 = 93; 
 global ind_OLT; ind_OLT = 94; 
 global ind_MEK; ind_MEK = 95; 
 global ind_ACT; ind_ACT = 96; 
 global ind_HNO3; ind_HNO3 = 97; 
 global ind_HKET; ind_HKET = 98; 
 global ind_ROH; ind_ROH = 99; 
 global ind_BEN; ind_BEN = 100; 
 global ind_ORAP; ind_ORAP = 101; 
 global ind_HOCl; ind_HOCl = 102; 
 global ind_KET; ind_KET = 103; 
 global ind_XYOP; ind_XYOP = 104; 
 global ind_ADCN; ind_ADCN = 105; 
 global ind_BALD; ind_BALD = 106; 
 global ind_MVK; ind_MVK = 107; 
 global ind_ETEP; ind_ETEP = 108; 
 global ind_BENP; ind_BENP = 109; 
 global ind_PER2; ind_PER2 = 110; 
 global ind_MCP; ind_MCP = 111; 
 global ind_TOLP; ind_TOLP = 112; 
 global ind_PER1; ind_PER1 = 113; 
 global ind_ADDC; ind_ADDC = 114; 
 global ind_MCTP; ind_MCTP = 115; 
 global ind_GLY; ind_GLY = 116; 
 global ind_HC8P; ind_HC8P = 117; 
 global ind_HCl; ind_HCl = 118; 
 global ind_XYLP; ind_XYLP = 119; 
 global ind_CSL; ind_CSL = 120; 
 global ind_LIMP; ind_LIMP = 121; 
 global ind_UALP; ind_UALP = 122; 
 global ind_MVKP; ind_MVKP = 123; 
 global ind_MGLY; ind_MGLY = 124; 
 global ind_DCB3; ind_DCB3 = 125; 
 global ind_MACR; ind_MACR = 126; 
 global ind_ISOP; ind_ISOP = 127; 
 global ind_MACP; ind_MACP = 128; 
 global ind_MOH; ind_MOH = 129; 
 global ind_BrAer; ind_BrAer = 130; 
 global ind_OLNN; ind_OLNN = 131; 
 global ind_APIP; ind_APIP = 132; 
 global ind_ONIT; ind_ONIT = 133; 
 global ind_OLTP; ind_OLTP = 134; 
 global ind_UALD; ind_UALD = 135; 
 global ind_RCO3; ind_RCO3 = 136; 
 global ind_ClO; ind_ClO = 137; 
 global ind_BrO; ind_BrO = 138; 
 global ind_Br; ind_Br = 139; 
 global ind_DCB2; ind_DCB2 = 140; 
 global ind_OP2; ind_OP2 = 141; 
 global ind_HC5P; ind_HC5P = 142; 
 global ind_OLI; ind_OLI = 143; 
 global ind_OLIP; ind_OLIP = 144; 
 global ind_OLND; ind_OLND = 145; 
 global ind_DCB1; ind_DCB1 = 146; 
 global ind_ACTP; ind_ACTP = 147; 
 global ind_MEKP; ind_MEKP = 148; 
 global ind_XO2; ind_XO2 = 149; 
 global ind_ACD; ind_ACD = 150; 
 global ind_HCHO; ind_HCHO = 151; 
 global ind_ClAer; ind_ClAer = 152; 
 global ind_O3P; ind_O3P = 153; 
 global ind_NO; ind_NO = 154; 
 global ind_O3; ind_O3 = 155; 
 global ind_MO2; ind_MO2 = 156; 
 global ind_KETP; ind_KETP = 157; 
 global ind_ALD; ind_ALD = 158; 
 global ind_HO; ind_HO = 159; 
 global ind_ORA2; ind_ORA2 = 160; 
 global ind_ETHP; ind_ETHP = 161; 
 global ind_NO2; ind_NO2 = 162; 
 global ind_NO3; ind_NO3 = 163; 
 global ind_HO2; ind_HO2 = 164; 
 global ind_HC3P; ind_HC3P = 165; 
 global ind_ACO3; ind_ACO3 = 166; 
 global ind_Cl; ind_Cl = 167; 

% Index declaration for fixed species in C                         
%   C(ind_spc)                                                     

 global ind_O2; ind_O2 = 168; 
 global ind_AIR; ind_AIR = 169; 
 global ind_H2; ind_H2 = 170; 
 global ind_CH4; ind_CH4 = 171; 
 global ind_N2; ind_N2 = 172; 
 global ind_H2O; ind_H2O = 173; 

% Index declaration for fixed species in FIX                       
%    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)                 

 global indf_O2; indf_O2 = 1; 
 global indf_AIR; indf_AIR = 2; 
 global indf_H2; indf_H2 = 3; 
 global indf_CH4; indf_CH4 = 4; 
 global indf_N2; indf_N2 = 5; 
 global indf_H2O; indf_H2O = 6; 
